export const collection = [
    "B2B Growth",
    "The Casted Podcast",
    "Short Wave",
    "Latvia Weekly",
    "Engineer Innovation",
    "Tech Talk Daily",
    "Startup Stories",
    "Mindful Makers",
    "The History Hour",
    "Informed Citizen",
    "Art of Coding",
    "Creative Culture",
    "Beyond the Screen",
    "Digital Nomads",
    "Modern Leadership",
    "Science Talk",
    "Design Matters",
    "True Crime Chronicles",
    "Marketing Mavericks",
    "The Psychology Podcast",
    "Planet Money",
    "Deep Dive Discussions",
    "Legal Legends",
    "Health & Wellness",
    "The Book Club"
];
